spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ligos
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  file: logs/dev.log
  level:
    org.springframework.web: debug
    ru.cs.ifmo.ligos: debug