spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ligos
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQL9Dialect

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
logging:
  file: logs/dev.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    ru.cs.ifmo.ligos: DEBUG