spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ligos
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  file: logs/dev.log
  level:
    org.springframework.web: debug
    ru.cs.ifmo.ligos: debug

security:
  oauth2:
    google:
      client:
        client-id: 977479910437-ohos40sgk72mjlim0i991a6rs5icap1v.apps.googleusercontent.com
        client-secret: iMoPD3lctQL2J4cU83IzuR9g
        authentication-scheme: form
        access-token-uri: https://www.googleapis.com/oauth2/v4/token
        user-authorization-uri: https://accounts.google.com/o/oauth2/auth
        scope: openid,email,profile


      resource:
        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
        prefer-token-info: true

    instagram:
      client:
        client-id: 6271f77c8978493fb39cd581189f3a3a
        client-secret: da7e46761aee4d3db562203a839fad1d
        authentication-scheme: form
        access-token-uri: https://api.instagram.com/oauth/access_token
        user-authorization-uri: https://api.instagram.com/oauth/authorize
        scope: openid,email,profile

        resource:
          user-info-uri: https://api.instagram.com/v1/users/self
